### ISSUE TITLE
Diag_axis object missing work

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#976]
**Is your feature request related to a problem? Please describe.**
The following things still need to be done for the diag_axis object:

- [x] set up the diag_axis_init top level #978 
- [x]  ~explore double linked to avoid setting limits to the diag_axis_object~
- [x] Add missing procedure to the diag_axis_object #982 
     ! PROCEDURE :: write_axis_metadata                                                                                 
     ! PROCEDURE :: write_axis_data                                                                                     
     ! PROCEDURE :: get_fileobj_type_needed (use the domain to figure out what fms2 fileobj to use)
- [x] error checking in the diag_axis_init procedure #978 
- [x] subaxis setup #1056 
- [x] ~move diag_copy_string~

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by uramirez8707** [comment]
Fixed in #1505
